### ISSUE TITLE
 у вас есть класс Input, есть класс Asker которые очень похожи по содержанию, пожумайте нужны ли оба этих класса и может быть стоит добавить интерфейс? 

### ISSUE THREAD

**Issue by Vasliska1** [nghiaphamhb/Programming#1]
https://github.com/nghiaphamhb/Programming/blob/aa11f693ffabd6b27f150a1ec4fc9187814ff13c/Lab%205/src/main/java/utility/Input.java#L8

**Comment by nghiaphamhb** [comment]
Я перенесли метод getScanner() от Input в Asker, и переименовал Input на InputMode , то есть InputMode может выбрать режим работы (с файлом или с пользователем), а Asker может взять информации от ввода
