### ISSUE TITLE
Я бы этот метод вынесла в другой класс

### ISSUE THREAD

**Issue by Vasliska1** [nghiaphamhb/Programming#10]
https://github.com/nghiaphamhb/Programming/blob/711b55ea0117c5d1f7fab01a11e905c7f9d8b04b/Lab%206/src/main/java/Server/Utility/SvRunner.java#L104

**Comment by nghiaphamhb** [comment]
Я написал StandardCommandManage (абстракный класс) и CommandManager. CommandManager следует StandardCommandManage и имеет ограничение в истории и автоматически загружает набор конкретных команд.
