### ISSUE TITLE
Очень большой метод. много в нем логике, нужно разбивать и возможно даже выносить в разные классы. помните принцип единственной ответственности?

### ISSUE THREAD

**Issue by Vasliska1** [nghiaphamhb/Programming#2]
https://github.com/nghiaphamhb/Programming/blob/aa11f693ffabd6b27f150a1ec4fc9187814ff13c/Lab%205/src/main/java/utility/Runner.java#L57

**Comment by nghiaphamhb** [comment]
Я переименовал scriptMode на runScript, и разбил часть (часть для получения информаций из файла) на другой класс ScriptReader. Сократил этот метод.
