### ISSUE TITLE
У класса много ответсвенности. Разделите на несколько - один класс будет читать, другой записывать.  И еще разделите методы тоже - вынесите логику где идет ТОЛЬКО взаимодействием с файлом от логики где идет взаимодействие с самой коллекцией

### ISSUE THREAD

**Issue by Vasliska1** [nghiaphamhb/Programming#3]
https://github.com/nghiaphamhb/Programming/blob/aa11f693ffabd6b27f150a1ec4fc9187814ff13c/Lab%205/src/main/java/Manager/DataManager.java#L19

**Comment by nghiaphamhb** [comment]
разбил DataManager на FileManager, FileReader, FileWriter. FileManager абстрактный класс, а FileReader FileWriter наследуют его. Но еще не понял вашу идею о логике
