### ISSUE TITLE
значение вынести в static final поле

### ISSUE THREAD

**Issue by Vasliska1** [nghiaphamhb/Programming#8]
https://github.com/nghiaphamhb/Programming/blob/711b55ea0117c5d1f7fab01a11e905c7f9d8b04b/Lab%206/src/main/java/Client/Utility/CliRunner.java#L49

**Comment by nghiaphamhb** [comment]
Я сейчас думаю об вашей просьбе, но давайте мне объяснить о своей идее. У меня Request, который включает в себя две части: название команды и его аргумент. Машину для поиска скриптов поставил в клиенте, и если она не успешно нашла скрипт, то присланный на сервер аргумент в Request равен -1 ( -1 это признак к неуспеху в поиске скрипта, который сервер понимает). Значит: 
public Request ( String nameCommand, Object argument); 
nameCommand = "execute_script";
if( Пользователь ввел эту команду без аргументов) -> argument.isEmty() -> сервер возвращает "неправильный синтаксис "
if( неуспешно нашли скриптов) -> argument = "-1" ->  сервер возвращает "не нашли таких скриптов "
if( успешно нашли скриптов) -> argument.equals(название скрипта) -> сервер разрешает клиенту работать то скрипт
Вообще final не можно использовать, потому что String[ ] command я поставил в цикле, чтобы постоянно брать ввод от пользователя при работе
